import Head from 'next/head';
import { TProduct } from '../utils/types';
import ProductGrid from '../components/ProductsGrid/ProductsGrid';
import { Main } from './index.styled';
import { client } from '../store/shopifyStore';

export const getServerSideProps = async () => {
  const products = await client.product.fetchAll();
  return {
    props: {
      products: JSON.parse(JSON.stringify(products)),
    },
  };
};

export default function Home({ products }: { products: TProduct[] }) {
  return (
    <>
      <Head>
        <title>Product page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <ProductGrid products={products} />
      </Main>
    </>
  );
}
